#!/bin/bash

function check_okay {
	if [ $? -ne 0 ]
	then
		exit 1
	fi
}


function do_one {
	cp $1 inlist
	check_okay
	rm -rf $2
	echo 'run' $1
	./rn1
	check_okay
  if [ ! -r $2 ]
  then
  	echo
  	echo "******************************************************************"
  	echo 'failed to create' $2 'when running' $1
  	echo "******************************************************************"
  	echo
  	exit 1
  fi
  echo
  echo 'finished' $1
  echo
	echo '***'
	echo '***'
	echo '***'
	echo '***'
	echo '***'
	echo '***'
	echo
}

date "+DATE: %Y-%m-%d%nTIME: %H:%M:%S"

echo "Running Mpinit = 1.0 MJup"
do_one models/Mpinit_1.0_MJup_1.0_ME/inlist_core_1.0_MJ_3.0_RJ_1.0_ME models/Mpinit_1.0_MJup_1.0_ME/planet_core_1.0_MJ_3.0_RJ_1.0_ME
do_one models/Mpinit_1.0_MJup_1.0_ME/inlist_evolve_1.0_MJ_3.0_RJ_1.0_ME models/Mpinit_1.0_MJup_1.0_ME/planet_evolve_1.0_MJ_3.0_RJ_1.0_ME.mod
date "+DATE: %Y-%m-%d%nTIME: %H:%M:%S"
echo "finished all inlists for make_planets"